// Shared animation primitives — one file per animation.
export { EO, ES } from "./easings"
export { SmoothScroll } from "./smoothScroll"
export { CustomCursor } from "./customCursor"
export { Magnetic } from "./magnetic"
export { TiltCard } from "./tiltCard"
export { StaggerWords } from "./staggerWords"
export { FadeUp } from "./fadeUp"
export { SlideIn } from "./slideIn"
export { WaveLetters } from "./waveLetters"
export { DepthExit } from "./depthExit"
export { GrainOverlay } from "./grainOverlay"
export { ScrambleText } from "./scrambleText"
export { SectionWrapper } from "./sectionWrapper"
export { ScrollProgress } from "./scrollProgress"
