import { motion, useInView, useReducedMotion } from "framer-motion"
import { useRef } from "react"
import { Link } from "react-router-dom"
import { V2Footer } from "../components/LegalFormKit"
import { V2Nav } from "../components/V2Kit"
import { usePageMeta } from "../hooks/usePageMeta"
import bookingImg from "../assets/ui-admin-dashboard.png"
import changeImg from "../assets/ui-changes-card.png"
import expenseImg from "../assets/ui-expenses-card.png"
import employeeImg from "../assets/role-traveller.jpg"
import financeImg from "../assets/role-finance-manager.jpg"
import travelTeamImg from "../assets/role-travel-team.jpg"
import experienceImg from "../assets/post-5pm.jpg"
import supplierImg from "../assets/partner-with-miraee.jpg"
import "./HomeV2Light.css"

const ease = [0.16, 1, 0.3, 1] as const
function Reveal({children,className="",delay=0}:{children:React.ReactNode;className?:string;delay?:number}){const ref=useRef<HTMLDivElement>(null),visible=useInView(ref,{once:true,margin:"-8% 0px"}),reduced=useReducedMotion();return <motion.div ref={ref} className={className} initial={{opacity:0,y:reduced?0:12}} animate={visible?{opacity:1,y:0}:{}} transition={{duration:reduced?0:.6,delay,ease}}>{children}</motion.div>}

const productChapters=[["Plan and book","Ask naturally. Miraee searches live inventory, understands preferences, and applies policy before presenting the right journey.",bookingImg,"Miraee admin dashboard showing travel spend, compliance, and active trips","/product#plan"],["Handle every change","When plans change, the agent finds alternatives, checks cost and policy, and brings you one clear decision.",changeImg,"Modification request showing requested flight changes and expected savings","/product#change"],["Close the expense loop","Bookings, payments, receipts, and policy stay connected so expense management becomes seamless.",expenseImg,"Trip expenses list with policy flags and auto-reconciled totals","/product#expense"]] as const
const workflow=[["Plan","Policy-safe itinerary","Under 60 sec"],["Book","Flight + hotel confirmed","1 approval"],["Protect","Disruption watched","Always on"],["Expense","Receipt reconciled","0 forms"]]
const roles=[["For employees","Ask once. Get a complete, policy-safe trip.","A trip that feels personal, not procedural.","4.8/5","traveler experience","/for-teams#employees"],["For finance","See committed spend before it becomes an expense.","Complete transparency over company expenditure.","Live","committed spend","/for-teams#finance"],["For travel teams","Set the rules once and run the program by exception.","No more managing every single booking and update.","24/7","agent + human care","/for-teams#travel-teams"]]
const roleImages=[employeeImg,financeImg,travelTeamImg]
const roleAlts=["Traveler working from an airport lounge","Finance manager reviewing performance data at his desk","Travel team collaborating around a tablet"]
const pains=[["5","separate systems","Disconnected systems","Booking, travel desks, payments, expense software, and employee benefits."],["12+","vendors","Vendors to manage","A dozen services stitched together, none sharing the full journey."],["0","built for them","The traveler does the work","The person actually traveling becomes the coordinator."]]
const handoffs=[["Traveler","Search + book","12 options","✈"],["Manager","Approve","Waiting","✓"],["Finance","Pay","Pending","$"],["Travel desk","Change","Ticket","↻"],["Accounting","Expense","Receipt","▤"]]
const differences=[["Global content, local experiences","Millions of properties and 500+ airlines, plus hyperlocal experiences no one else has digitized.","2M+ properties"],["A workforce of specialized agents","Booking, policy, negotiation, rebooking, expense and support agents that execute, not just answer.","6 agent roles"],["Human in the loop","Real support and oversight where it matters, so autonomy never means blind trust.","Human oversight"]]
const complete=[["Plan","Describe a trip naturally and get an in-policy itinerary in seconds.","Under 60 sec"],["Book","Flights, hotels, rail, and cars from live wholesale inventory.","Wholesale access"],["Expense","Receipts, coding, reports, and reconciliation prepared automatically.","0 forms"],["Change","The agent proactively rebooks disruptions within policy.","97%"],["Continuous support","Human-in-the-loop backup whenever a trip needs a real person.","Human backup"],["Personal travel","The same agent can plan employee trips without mixing company spend.","1 agent"]]
const compare=[["Natural-language planning","Not offered","Included"],["Live policy decisions","Partial","Included"],["Personal + business travel","Not offered","Included"],["Proactive disruption handling","Not offered","Included"],["Expense prepared automatically","Partial","Included"]]
const experiences=["Festivals and culture","Once-in-a-trip moments","Local performances","Markets and makers","The bleisure weekend","Food and discovery"]

export default function HomeV2(){usePageMeta("AI-Native Corporate Travel | Miraee","Miraee brings corporate travel management, expense automation, live policy and 24/7 support into one AI-native journey.");return <div className="m-site m-home"><a className="m-skip" href="#main">Skip to content</a><V2Nav active="/v2"/><main id="main">
  <section className="m-hero" aria-labelledby="v2-hero-title"><Reveal className="m-hero__copy"><p className="m-eyebrow">AI-native corporate travel</p><h1 id="v2-hero-title">AI-native employee travel Platform</h1><p className="m-lede">One intelligent platform for booking, travel management, and expenses. Miraee is built for business travel, and the personal trips people love.</p><div className="m-actions"><Link to="/book-a-demo">Book a demo</Link><a href="#product">Explore the platform <span aria-hidden="true">↓</span></a></div></Reveal></section>
  <section id="product" className="m-section"><Reveal className="m-section__head"><p className="m-eyebrow">One continuous system</p><h2>From “I need to go” to everything handled.</h2><p>A personal travel agent for employees. A real-time operating layer for finance and travel teams.</p></Reveal><div className="m-chapters">{productChapters.map(([title,copy,img,alt,href],i)=><Reveal className="m-chapter" key={title} delay={i*.05}><div className="m-chapter__copy"><span>0{i+1}</span><h3>{title}</h3><p>{copy}</p><Link to={href}>See how it works</Link></div><div className="m-chapter__media"><img src={img} alt={alt} loading="lazy"/></div></Reveal>)}</div></section>
  <section id="how-it-works" className="m-section m-how"><Reveal className="m-section__head"><p className="m-eyebrow">How it works</p><h2>Ask once. Keep moving.</h2><p>Miraee carries one continuous context through the entire journey. You never restart, repeat yourself, or manage the process.</p></Reveal><Reveal className="m-request"><span>Your request</span><blockquote>“Singapore next Tuesday. Window seat. Within policy.”</blockquote></Reveal><div className="m-workflow">{workflow.map(([t,c,m],i)=><Reveal className="m-step" key={t} delay={i*.07}><span>0{i+1}</span><small>{t}</small><h3>{c}</h3><strong>{m}</strong></Reveal>)}</div></section>
  <section className="m-section m-problem"><Reveal className="m-section__head"><p className="m-eyebrow">The problem</p><h2>Every handoff fragments the journey.</h2><p>Every handoff loses context and adds another system for the traveler to manage.</p></Reveal><Reveal className="m-handoffs"><div className="m-handoffs__trip"><span>One employee trip</span><strong>SFO <i aria-hidden="true">→</i> SIN</strong><small>No one sees the whole trip</small></div><div className="m-handoffs__owners">{handoffs.map(([owner,job,state,icon],i)=><div key={job}><span>0{i+1}</span><b aria-hidden="true">{icon}</b><small>{owner}</small><strong>{job}</strong><em>{state}</em></div>)}</div></Reveal><div className="m-pain-grid">{pains.map(([n,l,t,c])=><Reveal className="m-pain" key={t}><strong>{n}</strong><small>{l}</small><h3>{t}</h3><p>{c}</p></Reveal>)}</div></section>
  <section className="m-section m-platform"><Reveal className="m-section__head"><p className="m-eyebrow">The platform</p><h2>Global reach. Personal execution.</h2></Reveal><div className="m-list">{differences.map(([t,c,m],i)=><Reveal className="m-list__row" key={t}><span>0{i+1}</span><h3>{t}</h3><p>{c}</p><strong>{m}</strong></Reveal>)}</div><Reveal className="m-section__head m-complete-head"><p className="m-eyebrow">The complete platform</p><h2>Six capabilities. One continuous context.</h2></Reveal><div className="m-complete">{complete.map(([t,c,m])=><Reveal className="m-complete__item" key={t}><h3>{t}</h3><p>{c}</p><strong>{m}</strong></Reveal>)}</div></section>
  <section id="outcomes" className="m-section"><Reveal className="m-section__head"><p className="m-eyebrow">Designed for everyone</p><h2>Less work. Better journeys.</h2></Reveal><div className="m-roles">{roles.map(([t,c,e,n,l,href],i)=><Reveal className="m-role" key={t}><img className="m-role__photo" src={roleImages[i]} alt={roleAlts[i]} loading="lazy"/><span>{t}</span><h3>{c}</h3><p>{e}</p><strong>{n}</strong><small>{l}</small><Link to={href} className="m-role__link">See how it works <span aria-hidden="true">→</span></Link></Reveal>)}</div></section>
  <section className="m-section m-comparison"><Reveal className="m-section__head"><p className="m-eyebrow">The difference</p><h2>Not another booking tool. A new operating model.</h2><p>Legacy tools wait for clicks. Miraee understands intent, works within your policy, and completes the trip.</p></Reveal><Reveal><div className="m-table" role="table" aria-label="Miraee compared with a legacy travel management company"><div className="m-table__head" role="row"><b role="columnheader">Capability</b><b role="columnheader">Legacy TMC</b><b role="columnheader">Miraee</b></div>{compare.map(r=><div role="row" key={r[0]}><span role="cell">{r[0]}</span><span role="cell" data-label="Legacy TMC">{r[1]}</span><strong role="cell" data-label="Miraee">{r[2]}</strong></div>)}</div><Link to="/why-miraee#compare" className="m-comparison__more">See the full comparison <span aria-hidden="true">↗</span></Link></Reveal></section>
  <section className="m-section m-business"><Reveal className="m-section__head"><p className="m-eyebrow">The business case</p><h2>Loved by employees. Trusted by finance.</h2></Reveal><div className="m-business__numbers"><Reveal><strong>20-30%</strong><p>Wholesale savings, validated apples-to-apples versus incumbents</p></Reveal><Reveal><strong>97%</strong><p>Of the journey managed by the agent, end to end</p></Reveal><Reveal><strong>1</strong><p>Platform for business and personal travel alike</p></Reveal></div><p className="m-note">Illustrative platform outcomes. Actual savings and automation rates vary by travel program, inventory, policy, and adoption.</p></section>
  <section id="security" className="m-security"><Reveal><p className="m-eyebrow">Enterprise foundations</p><h2>Fast for people.<br/>Safe for the business.</h2><p>Every action is governed, permissioned, traceable, and ready for enterprise controls.</p></Reveal><div className="m-security__marks"><Link to="/security#certifications"><strong>SOC 2</strong><small>Operational controls</small></Link><Link to="/security#governance"><strong>SSO / SCIM</strong><small>Identity management</small></Link><Link to="/security#certifications"><strong>GDPR</strong><small>Privacy by design</small></Link><Link to="/security#governance"><strong>Audit logs</strong><small>Every agent action</small></Link></div></section>
  <section className="m-section m-experiences"><Reveal className="m-section__head"><p className="m-eyebrow">Experiences</p><h2>Not bookable anywhere else.</h2><p>The city after 5pm, the festival, or the family weekend bolted onto a work trip, booked separately from company spend in one tap.</p></Reveal><Reveal className="m-experiences__photo"><img src={experienceImg} alt="Hong Kong skyline and harbor illuminated after dark" width="2000" height="1333" loading="lazy"/></Reveal><div className="m-experience-grid">{experiences.map((x,i)=><Reveal className="m-experience" key={x}><span>{String(i+1).padStart(2,"0")}</span><h3>{x}</h3></Reveal>)}</div></section>
  <section id="partners" className="m-section m-partners"><Reveal><p className="m-eyebrow">For airlines and suppliers</p><h2>Be part of your travelers’ best experiences.</h2><p>Miraee puts partner brands in front of premium, high-frequency travelers across both business and personal trips, with content they control.</p><Link to="/book-a-demo">Partner with Miraee <span aria-hidden="true">↗</span></Link></Reveal><Reveal className="m-partners__photo"><img src={supplierImg} alt="Business traveler receiving attentive service in a premium aircraft cabin" loading="lazy"/></Reveal></section>
  <section className="m-cta"><Reveal><p className="m-eyebrow">See the agent in action</p><h2>See it, handle<br/>a real trip, live.</h2><p>Bring a real trip. We’ll show you how Miraee handles it in twenty minutes.</p><Link to="/book-a-demo">Book your demo <span aria-hidden="true">↗</span></Link></Reveal></section>
  </main><V2Footer/></div>}
